#!/usr/bin/env bash

# this is a simple config for herbstluftwm

hc() {
    herbstclient "$@"
}

hc emit_hook reload

# remove all existing keybindings
hc keyunbind --all

# keybindings
Mod=Mod4   # Use the super key as the main modifier

hc keybind $Mod-Shift-q quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-Shift-c close

# frame layouts and split behavior
hc keybind $Mod-Control-0 set_layout vertical      # default
hc keybind $Mod-Control-1 set_layout horizontal    # side-by-side 
hc keybind $Mod-Control-2 set_layout max           # max
hc keybind $Mod-Control-3 set-layout grid          # grid

# Program shortcuts
hc keybind $Mod-Return spawn termite
hc keybind $Mod-c spawn code
hc keybind $Mod-q spawn qutebrowser
hc keybind $Mod-w spawn qutebrowser.wrapper 
hc keybind $Mod-e spawn qutebrowser.boxboat
hc heybind $Mod-v spawn termite -e vim
hc keybind $Mod-k spawn kodi
hc keybind $Mod-d spawn dolphin --platformtheme qt5ct
hc keybind $Mod-m spawn rofi "Iosevka Term SS08 Light 14" -show drun -modi drun,ssh -display-drun "run: "
hc keybind Alt-Tab spawn rofi "Iosevka Term SS08 Light 14" -theme window -show window -modi window -display-window "windows: "
hc keybind $Mod-z spawn /home/daniel/scripts/darkmode
hc keybind $Mod-a spawn /home/daniel/scripts/lightmode
hc keybind $Mod-Alt-p spawn ~/scripts/shots snippet
hc keybind $Mod-Alt-o spawn ~/scripts/shots screen

# fn keybinds
 hc keybind XF86MonBrightnessDown spawn /usr/bin/light -U 5
 hc keybind XF86MonBrightnessUp   spawn /usr/bin/light -A 5

# basic movement
# focusing clients
hc keybind $Mod-Left  focus left
hc keybind $Mod-Down  focus down
hc keybind $Mod-Up    focus up
hc keybind $Mod-Right focus right
hc keybind $Mod-h     focus left
hc keybind $Mod-j     focus down
hc keybind $Mod-k     focus up
hc keybind $Mod-l     focus right

# moving clients
hc keybind $Mod-Shift-Left  shift left
hc keybind $Mod-Shift-Down  shift down
hc keybind $Mod-Shift-Up    shift up
hc keybind $Mod-Shift-Right shift right
hc keybind $Mod-Shift-h     shift left
hc keybind $Mod-Shift-j     shift down
hc keybind $Mod-Shift-k     shift up
hc keybind $Mod-Shift-l     shift right

# moving clients to different tags/desktops
hc keybind $Mod-Shift-1     move 1
hc keybind $Mod-Shift-2     move 2
hc keybind $Mod-Shift-3     move 3
hc keybind $Mod-Shift-4     move 4

# splitting frames
# create an empty frame at the specified direction
hc keybind $Mod-u       split   top  0.5
hc keybind $Mod-o       split   left   0.5
# let the current frame explode into subframes
hc keybind $Mod-Control-space split explode

# resizing frames
resizestep=0.005
hc keybind $Mod-Control-h       resize left +$resizestep
hc keybind $Mod-Control-j       resize down +$resizestep
hc keybind $Mod-Control-k       resize up +$resizestep
hc keybind $Mod-Control-l       resize right +$resizestep
hc keybind $Mod-Control-Left    resize left +$resizestep
hc keybind $Mod-Control-Down    resize down +$resizestep
hc keybind $Mod-Control-Up      resize up +$resizestep
hc keybind $Mod-Control-Right   resize right +$resizestep

# tags
tag_names=( 1 2 3 4 5 6 7 8 9 )
tag_keys=( {1..9} 0)

hc rename default "${tag_names[0]}" || true
for i in ${!tag_names[@]} ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# cycle through tags
hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma  use_index -1 --skip-visible

# layouting
hc keybind $Mod-r remove
hc keybind $Mod-s floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-p pseudotile togglete an empty f
# The following cycles through the available layouts within a frame, but skips
# layouts, if the layout change wouldn't affect the actual window positions.
# I.e. if there are two windows within a frame, the grid layout is skipped.
hc keybind $Mod-space                                                           \
            or , and . compare tags.focus.curframe_wcount = 2                   \
                     . cycle_layout +1 vertical horizontal max vertical grid    \
               , cycle_layout +1

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Shift-Button1 resize

# focus
hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-g cycle
hc keybind $Mod-i jumpto urgent

# theme
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_active_color '#f7f8f3'
hc set frame_border_normal_color '#f7f8f3'
hc set frame_bg_normal_color '#f7f8f3'
hc set frame_bg_active_color '#f7f8f3'

hc set frame_border_width 0
hc set frame_bg_transparent 1
hc set frame_transparent_width 0
hc set frame_gap 0

hc attr theme.active.color '#4e9bcf'
hc attr theme.normal.color '#c9c5cb'
hc attr theme.urgent.color '#f7f8f3'
hc attr theme.inner_width 0
tc attr theme.inner_color '#f7f8f3'
hc attr theme.border_width 4
hc attr theme.floating.border_width 4
hc attr theme.floating.outer_width 2
hc attr theme.floating.outer_color '#c9c5cb'
hc attr theme.active.inner_color '#f7f8f3'
hc attr theme.active.outer_color '#4e9bcf'
hc attr theme.background_color '#f7f8f3'

hc set window_gap 4
hc set frame_padding -2
hc set smart_window_surroundings 0
hc set smart_frame_surroundings 0
hc set mouse_recenter_gap 0

# rules
hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=on # normally focus new clients
#hc rule focus=off # normally do not focus new clients
# give focus to most common terminals
#hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=off
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

# unlock, just to be sure
hc unlock

herbstclient set tree_style '╾│ ├└╼─┐'

# do multi monitor setup here, e.g.:
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:
hc detect_monitors

# padding for panel
hc pad 0 28 2 2 2

# start programs once
{
    command="silent new_attr bool my_not_first_autostart"

    if hc $command;
    then
        xfce4-power-manager &
        tint2 &
        volumeicon &
        redshift-gtk &
        picom -b --unredir-if-possible &
        nitrogen --restore &
        dunst &
        bluetoothctl connect E2:34:86:6B:05:BC &
    fi      
}

hc setenv QT_QPA_PLATFORMTHEME qt5ct
hc setenv npm_config_prefix ~/.node_modules
