#!/bin/bash

if [ "$(basename "$@")" != qutebrowser ]; then
    exec /usr/bin/qutebrowser "$@" --qt-flag ignore-gpu-blacklist --qt-flag enable-gpu-rasterization --qt-flag enable-native-gpu-memory-buffers --qt-flag num-raster-threads=4 --qt-flag use-gl=desktop --qt-flag enable-accelerated-video-decode
fi
exit 0
